name: Docker Scout Scan

on:
  pull_request:
    paths:
      - '**/Dockerfile*'

permissions:
  contents: read
  pull-requests: write
  security-events: write

jobs:
  scout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Image
        run: docker build -t test-image:latest .

      - name: Docker Scout CVE Scan
        uses: docker/scout-action@v1
        with:
          command: cves
          image: test-image:latest
          sarif-file: scout-results.sarif
          summary: true

      - name: Upload to Security Tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: scout-results.sarif