name: Trivy Docker Security Scan

on:
  pull_request:
    paths:
      - '**/Dockerfile*'
      - '**/*.dockerfile'

permissions:
  contents: read
  security-events: write

jobs:
  docker-security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t local-image:latest .

      - name: Trivy Docker Image Scan
        uses: aquasecurity/trivy-action@master
        continue-on-error: true
        env:
          TRIVY_DEBUG: true
        with:
          image-ref: "local-image:latest"
          format: "sarif"
          output: "trivy-results.sarif"
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"

      - name: Upload Trivy results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: "trivy-results.sarif"