name: Checkov - IaC Scan

on:
  pull_request:
    paths:
      - '**.tf'

jobs:
  checkov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Instalar Checkov
        run: pip install checkov

      - name: Rodar Checkov
        run: checkov -d . --quiet